repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: check-added-large-files
        args: ['--maxkb=600']
    -   id: check-yaml
    -   id: check-json
    -   id: check-toml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-docstring-first
-   repo: https://github.com/python-poetry/poetry
    rev: 1.8.0
    hooks:
    -   id: poetry-check
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.4.2
  hooks:
    - id: ruff
      args: [ --fix ]
    - id: ruff-format
